import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "MinhVo",
  title: "MinhVo | Front-end Engineer",
  description: "MinhVo is a software engineer who loves to build things with code.",
  origin: "https://minhvo.vercel.app",
  keywords: [
    "MinhVo",
    "Front-end Engineer",
    "Developer",
    "Engineering",
    "Front-end",
    "Developer",
    "MinhVo portfolio",
    "MinhVo blog",
    "MinhVo projects",
    "MinhVo experience",
    "MinhVo education",
    "MinhVo skills",
    "MinhVo contact",
    "MinhVo CV",
    "MinhVo TIL",
    "MinhVo blog",
    "Software Engineer",
    "Front-end Engineer",
    "Developer",
    "Engineering",
    "Front-end",
    "Developer",
  ],
  og: "https://minhvo.vercel.app/og.png",
  creator: {
    name: "MinhVo",
    url: "https://minhvo.vercel.app",
  },
  socials: {
    github: "https://github.com/minhomega",
    x: "https://x.com/minhomega",
  },
  siteUrl: "https://minhvo.vercel.app",
}
