import { SiteConfig } from "@/types";

export const siteConfig: SiteConfig = {
  name: "MinhVo",
  title: "MinhVo | Front-end Engineer",
  description: "Hey there! I'm MinhVo, a passionate Front-End Engineer who brings ideas to life through elegant code and delightful user experiences. I specialize in crafting modern web applications that make a difference.",
  origin: "https://minhvo.is-a.dev",
  keywords: [
    "MinhVo",
    "Front-end Engineer",
    "Software Engineer",
    "Full-stack Engineer",
    "Web Developer",
    "Mobile Developer",
    "Engineering",
    "Development",
    "MinhVo portfolio",
    "MinhVo blog", 
    "MinhVo projects",
    "MinhVo experience",
    "MinhVo education",
    "MinhVo skills",
    "MinhVo contact",
    "MinhVo CV",
    "MinhVo TIL",
    "React",
    "Next.js",
    "React Native",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "TailwindCSS",
    "Web Development",
    "Mobile Development",
    "UI/UX",
    "Responsive Design",
    "Web Performance",
    "Web Accessibility",
    "SEO",
    "Git",
    "GitHub",
    "REST API",
    "GraphQL",
    "State Management",
    "Testing",
    "CI/CD",
    "Agile",
    "Scrum"
  ],
  og: "https://minhvo.is-a.dev/og.png",
  creator: {
    name: "MinhVo",
    url: "https://minhvo.is-a.dev",
  },
  socials: {
    github: "https://github.com/minhomega",
    x: "https://x.com/minhomega",
  },
  siteUrl: "https://minhvo.is-a.dev",
}
